version: '3.8'

services:
  # Next.js Application
  nextjs-app:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    container_name: invoice-reconciler-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - PRIVATE_SUPABASE_SERVICE_KEY=${PRIVATE_SUPABASE_SERVICE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID=${SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID}
      - SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET=${SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET}
      - NEXT_PUBLIC_PRODUCTNAME=${NEXT_PUBLIC_PRODUCTNAME}
      - NEXT_PUBLIC_SSO_PROVIDERS=${NEXT_PUBLIC_SSO_PROVIDERS}
      - NEXT_PUBLIC_THEME=${NEXT_PUBLIC_THEME}
      - NEXT_PUBLIC_TIERS_NAMES=${NEXT_PUBLIC_TIERS_NAMES}
      - NEXT_PUBLIC_TIERS_PRICES=${NEXT_PUBLIC_TIERS_PRICES}
      - NEXT_PUBLIC_TIERS_DESCRIPTIONS=${NEXT_PUBLIC_TIERS_DESCRIPTIONS}
      - NEXT_PUBLIC_TIERS_FEATURES=${NEXT_PUBLIC_TIERS_FEATURES}
      - NEXT_PUBLIC_POPULAR_TIER=${NEXT_PUBLIC_POPULAR_TIER}
      - NEXT_PUBLIC_COMMON_FEATURES=${NEXT_PUBLIC_COMMON_FEATURES}
      - NEXT_PUBLIC_GOOGLE_TAG=${NEXT_PUBLIC_GOOGLE_TAG}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_WEBHOOK_SECRET=${N8N_WEBHOOK_SECRET}
    ports:
      - "3000:3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - nextjs_uploads:/app/uploads

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: invoice-reconciler-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates in production
    depends_on:
      - nextjs-app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  nextjs_uploads:
    driver: local 